const Client = require("./src/CocoaClient.js")
const client = new Client({fetchAllMembers: true})
require("./src/ProtoTypes.js").start()
require("dotenv").config()
client.loadCommands("./commands")
client.loadEvents("./events")
client.login(process.env.TOKEN)
console.log("Starting...")